export const AUTH = {
  LOGIN_SUCCESSFUL: 'LOGIN_SUCCESSFUL',
  LOGIN_ERROR: 'LOGIN_ERROR',
  LOGOUT: 'LOGOUT',
};

export const FAVORITE = {
  ADD_FAVORITE: 'ADD_FAVORITE',
  REMOVE_FAVORITE: 'REMOVE_FAVORITE',
};

export const HISTORY = {
  ADD_HISTORY: 'ADD_HISTORY',
  REMOVE_HISTORY: 'REMOVE_HISTORY',
};
